name: Crawl links

on:
  # 手動実行も可能にする
  workflow_dispatch:
  
  # 毎日午前3時に実行（UTCベース）
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  run-crawl-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run crawl_links.py
        run: |
          python scripts/crawl_links.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update articles.json via GitHub Actions (Daily)"
          file_pattern: data/articles.json
